"""empty message

Revision ID: 312f95a7bc7c
Revises: 
Create Date: 2022-10-14 13:16:33.685034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312f95a7bc7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'news', ['news_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['news_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###
